allowed.origins: "*"
server:
  port: 8090
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: Magalu

project:
  version: @project.version@
  description: @project.description@

magalu:
  jwt:
    secret: Cl4ss1c1n3F0rJWTS3cr3tSignatureAlgorithmM0vi3sF0rL1f3512bitsKeySize
    expiration: 1000000
  integration:
    postmon: "https://api.postmon.com.br"

rollbar:
  token: ae2c5730f60040b8a68a18cc5053b1a4
  environment: production
  version: 1.0.0

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000