allowed.origins: "*"
server:
  port: 8090
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: Magalu

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics
  metrics:
    export:
      atlas:
        enabled: false
  endpoint:
    health:
      show-details: "ALWAYS"

project:
  version: @project.version@
  description: @project.description@

magalu:
  jwt:
    secret: Cl4ss1c1n3F0rJWTS3cr3tSignatureAlgorithmM0vi3sF0rL1f3512bitsKeySize
    expiration: 1000000
  integration:
    postmon: "https://api.postmon.com.br"

rollbar:
  token: adcd6aa3279343b2a7f328348c2311aa
  environment: production

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000